# Generated by Django 4.1 on 2022-08-17 10:01

from django.db import migrations, models
import django.db.models.deletion
import novaposhta_api.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NP_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=36, unique=True)),
                ('Description', models.CharField(max_length=50)),
                ('DescriptionRu', models.CharField(max_length=50)),
                ('AreasCenter', models.CharField(max_length=36)),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'NP Area',
                'verbose_name_plural': 'NP Areas',
            },
            bases=(novaposhta_api.mixins.NP_JSONDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NP_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=36, unique=True)),
                ('Description', models.CharField(max_length=50)),
                ('DescriptionRu', models.CharField(max_length=50)),
                ('json', models.TextField()),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='novaposhta_api.np_area')),
            ],
            options={
                'verbose_name': 'NP City',
                'verbose_name_plural': 'NP Cities',
            },
            bases=(novaposhta_api.mixins.NP_JSONDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NP_WareHouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=36, unique=True)),
                ('Description', models.CharField(max_length=50)),
                ('DescriptionRu', models.CharField(max_length=50)),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'NP WareHouse Type',
                'verbose_name_plural': 'NP WareHouse Types',
            },
            bases=(novaposhta_api.mixins.NP_JSONDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NP_WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=36, unique=True)),
                ('WarehouseStatus', models.CharField(max_length=36)),
                ('SiteKey', models.PositiveIntegerField()),
                ('Description', models.CharField(max_length=99)),
                ('DescriptionRu', models.CharField(max_length=99)),
                ('DenyToSelect', models.BooleanField()),
                ('Number', models.PositiveIntegerField()),
                ('MaxDeclaredCost', models.PositiveIntegerField()),
                ('TotalMaxWeightAllowed', models.PositiveIntegerField()),
                ('PlaceMaxWeightAllowed', models.PositiveIntegerField()),
                ('DimensionsMaxWidth', models.PositiveIntegerField()),
                ('DimensionsMaxHeight', models.PositiveIntegerField()),
                ('DimensionsMaxLength', models.PositiveIntegerField()),
                ('json', models.TextField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_city')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_warehousetype')),
            ],
            options={
                'verbose_name': 'NP Warehouses',
                'verbose_name_plural': 'NP Warehouse',
            },
            bases=(novaposhta_api.mixins.NP_JSONDataMixin, models.Model),
        ),
    ]
