# Generated by Django 4.1 on 2022-08-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NP_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=36)),
                ('areas_center', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='NP_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=36)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='novaposhta_api.np_area')),
            ],
        ),
    ]
