# Generated by Django 4.1 on 2022-08-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NP_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('description_ru', models.CharField(max_length=50)),
                ('areas_center', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='NP_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('description_ru', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='novaposhta_api.np_area')),
            ],
        ),
        migrations.CreateModel(
            name='NP_WareHouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('description_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NP_WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('siteKey', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=99)),
                ('description_ru', models.CharField(max_length=99)),
                ('denyToSelect', models.BooleanField()),
                ('number', models.PositiveIntegerField()),
                ('maxDeclaredCost', models.PositiveIntegerField()),
                ('totalMaxWeightAllowed', models.PositiveIntegerField()),
                ('placeMaxWeightAllowed', models.PositiveIntegerField()),
                ('dimensions_max_width', models.PositiveIntegerField()),
                ('dimensions_max_height', models.PositiveIntegerField()),
                ('dimensions_max_length', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_warehousetype')),
            ],
        ),
    ]
