# Generated by Django 4.1 on 2022-08-17 10:22

from django.db import migrations, models
import novaposhta_api.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NP_CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=36, unique=True)),
                ('Description', models.CharField(max_length=36)),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'NP Cargo Type',
                'verbose_name_plural': 'NP Cargo Types',
            },
            bases=(novaposhta_api.mixins.NP_JSONDataMixin, models.Model),
        ),
    ]
