# Generated by Django 4.1 on 2022-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NP_WareHouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=36)),
            ],
        ),
    ]
