# Generated by Django 4.1 on 2022-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='np_warehouse',
            name='status',
            field=models.CharField(default='Working', max_length=36),
        ),
    ]
