# Generated by Django 4.1 on 2022-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta_api', '0002_np_warehousetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NP_WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=99)),
                ('number', models.CharField(max_length=36)),
                ('ref', models.CharField(max_length=36)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='novaposhta_api.np_warehousetype')),
            ],
        ),
    ]
