# Generated by Django 4.1 on 2022-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta_api', '0003_np_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='np_area',
            name='ref',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='np_city',
            name='ref',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='np_warehouse',
            name='ref',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='np_warehousetype',
            name='ref',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
